In [1]:
#lefenshtein distance

In [2]:
import torch
import numpy as np

In [13]:
torch.manual_seed(1337)

In [14]:
#range
max = 61
min = 0

out = (max-min)*torch.rand((2, 5)) + min

In [15]:
out = out.type(torch.int8)
out

tensor([[ 4, 30, 38, 25, 12],
        [ 1, 35, 42, 10, 15]], dtype=torch.int8)

In [17]:
import Levenshtein

In [22]:
s1 = "hello how are you"
s2 = "holla how are y2u"

In [23]:
Levenshtein.distance(s1, s2)

3

In [33]:
def metric(pred: torch.tensor, target:torch.tensor):
    # shouldn't count pad token 
    # if i would use it in model
    full_distance = 0
    N = 0
    for i in range(len(pred)):# through batches
        for j in range(len(pred[i])): # through signs
            p = encode(pred[i][j])
            t = encode(target[i][j])
            # i should cut words so that there is no pad tokens
            # this is gonna count pad token pepesad        
            distance = Levenshtein.distance(p, t)
            full_distance += distance
            N += len(p) + len(t)
        
    return (N - D) / N


In [34]:
metric(out, out + 10)

TypeError: iteration over a 0-d tensor

In [2]:
import numpy as np
y = np.load('../data/y_train.npy')
y.shape

(54719, 128)

In [3]:
y

array([[18,  0, 34, ..., 59, 59, 59],
       [39, 36, 45, ..., 59, 59, 59],
       [16, 18, 23, ..., 59, 59, 59],
       ...,
       [24, 24, 19, ..., 59, 59, 59],
       [39, 51, 51, ..., 59, 59, 59],
       [23, 15, 17, ..., 59, 59, 59]], dtype=int8)

In [7]:
y[0, 20:50]

array([59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59,
       59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59], dtype=int8)